"use client";

import { useRef, useCallback } from "react";

interface FlyerGeneratorProps {
  profile: {
    breed: string;
    color: string;
    size: string;
    distinguishingFeatures: string[];
    hasCollar: boolean;
    collarDescription?: string;
    estimatedAge: string;
    gender?: string;
  };
  photoPreview: string;
  location: string;
}

export default function FlyerGenerator({
  profile,
  photoPreview,
  location,
}: FlyerGeneratorProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const generateFlyer = useCallback(async () => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    canvas.width = 800;
    canvas.height = 1100;

    // Background
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, 800, 1100);

    // Header bar
    ctx.fillStyle = "#f97316";
    ctx.fillRect(0, 0, 800, 120);
    ctx.fillStyle = "#ffffff";
    ctx.font = "bold 56px Arial, sans-serif";
    ctx.textAlign = "center";
    ctx.fillText("FOUND DOG", 400, 82);

    // Photo
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      // Photo container
      const photoY = 140;
      const photoSize = 350;
      ctx.fillStyle = "#f3f4f6";
      ctx.fillRect(
        400 - photoSize / 2 - 5,
        photoY - 5,
        photoSize + 10,
        photoSize + 10
      );

      // Draw photo maintaining aspect ratio
      const scale = Math.max(
        photoSize / img.width,
        photoSize / img.height
      );
      const sw = photoSize / scale;
      const sh = photoSize / scale;
      const sx = (img.width - sw) / 2;
      const sy = (img.height - sh) / 2;
      ctx.drawImage(
        img,
        sx,
        sy,
        sw,
        sh,
        400 - photoSize / 2,
        photoY,
        photoSize,
        photoSize
      );

      // Details section
      let y = photoY + photoSize + 40;
      ctx.fillStyle = "#1a1a1a";
      ctx.textAlign = "left";
      const leftCol = 80;

      const drawDetail = (label: string, value: string) => {
        ctx.font = "bold 22px Arial, sans-serif";
        ctx.fillStyle = "#f97316";
        ctx.fillText(label, leftCol, y);
        ctx.font = "22px Arial, sans-serif";
        ctx.fillStyle = "#1a1a1a";
        ctx.fillText(value, leftCol + 200, y);
        y += 36;
      };

      drawDetail("Breed:", profile.breed);
      drawDetail("Color:", profile.color);
      drawDetail("Size:", profile.size.charAt(0).toUpperCase() + profile.size.slice(1));
      drawDetail("Age:", profile.estimatedAge.charAt(0).toUpperCase() + profile.estimatedAge.slice(1));
      if (profile.gender && profile.gender !== "unknown") {
        drawDetail("Gender:", profile.gender.charAt(0).toUpperCase() + profile.gender.slice(1));
      }
      drawDetail(
        "Collar:",
        profile.hasCollar
          ? profile.collarDescription || "Yes"
          : "None observed"
      );

      // Features
      if (profile.distinguishingFeatures.length > 0) {
        y += 10;
        ctx.font = "bold 22px Arial, sans-serif";
        ctx.fillStyle = "#f97316";
        ctx.fillText("Features:", leftCol, y);
        y += 30;
        ctx.font = "20px Arial, sans-serif";
        ctx.fillStyle = "#1a1a1a";
        profile.distinguishingFeatures.forEach((f) => {
          ctx.fillText(`  - ${f}`, leftCol, y);
          y += 28;
        });
      }

      // Location bar
      y += 20;
      ctx.fillStyle = "#fef3c7";
      ctx.fillRect(40, y, 720, 50);
      ctx.fillStyle = "#92400e";
      ctx.font = "bold 22px Arial, sans-serif";
      ctx.textAlign = "center";
      ctx.fillText(`Found near: ${location}`, 400, y + 33);

      // Contact section
      y += 80;
      ctx.fillStyle = "#1a1a1a";
      ctx.font = "bold 24px Arial, sans-serif";
      ctx.fillText("Is this your dog? Contact:", 400, y);
      y += 40;
      ctx.font = "28px Arial, sans-serif";
      ctx.fillStyle = "#f97316";
      ctx.fillText("[YOUR PHONE / EMAIL HERE]", 400, y);

      // QR code placeholder
      y += 50;
      ctx.strokeStyle = "#d1d5db";
      ctx.lineWidth = 2;
      ctx.strokeRect(340, y, 120, 120);
      ctx.fillStyle = "#9ca3af";
      ctx.font = "14px Arial, sans-serif";
      ctx.fillText("QR Code", 400, y + 65);

      // Footer
      ctx.fillStyle = "#f97316";
      ctx.fillRect(0, 1060, 800, 40);
      ctx.fillStyle = "#ffffff";
      ctx.font = "16px Arial, sans-serif";
      ctx.fillText("Generated by PawsitiveID - pawsitiveid.vercel.app", 400, 1085);

      // Trigger download
      const link = document.createElement("a");
      link.download = `PawsitiveID-Found-Dog-Flyer.png`;
      link.href = canvas.toDataURL("image/png");
      link.click();
    };
    img.src = photoPreview;
  }, [profile, photoPreview, location]);

  return (
    <div className="glass-card p-6 max-w-2xl mx-auto text-center">
      <h2 className="text-2xl font-bold gradient-text mb-2">
        Generate Flyer
      </h2>
      <p className="text-gray-400 text-sm mb-4">
        Create a printable &quot;Found Dog&quot; flyer with the AI-generated profile.
        Print it out and post it around where you found the dog.
      </p>
      <button onClick={generateFlyer} className="glow-btn text-white font-bold py-3 px-8 rounded-xl text-lg">
        Download Flyer (PNG)
      </button>
      <canvas ref={canvasRef} className="hidden" />
    </div>
  );
}
